<template><main class="container portal"><header><router-link to="/cases">← 公开案例库</router-link><p class="eyebrow">TEACHER RESOURCES</p><h1>教师案例区</h1><p>以下案例已开放给教师账号。进入案例详情可查看教学指导手册及课堂材料。</p></header><p v-if="loading" class="empty">加载中…</p><p v-else-if="!cases.length" class="empty">当前没有教师可访问的已发布案例。</p><div class="cards"><router-link v-for="item in cases" :key="item.case_code" :to="`/cases/${item.case_code}`"><small>{{item.course_name}} · {{item.grade_year}} · {{visibility[item.permission_status]}}</small><h2>{{item.title}}</h2><p>{{item.introduction}}</p><span>{{item.topic_name}}　→</span></router-link></div><button class="logout" @click="logout">退出教师登录</button></main></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { teacherApi } from '../../api'
const router=useRouter(),cases=ref<any[]>([]),loading=ref(true),visibility:Record<string,string>={public:'公开',campus:'校内',classroom:'课堂授权'}
async function logout(){localStorage.removeItem('banshan_token');localStorage.removeItem('banshan_role');router.push('/teacher/login')}
onMounted(async()=>{try{cases.value=await teacherApi.getCases()}catch(e){console.error(e)}finally{loading.value=false}})
</script>
<style scoped>.portal{padding:60px 0 90px}header{max-width:700px;padding-bottom:35px;border-bottom:1px solid var(--c-line)}header>a{font-size:13px;color:var(--c-muted)}.eyebrow{margin-top:40px;font-size:11px;letter-spacing:.15em;color:var(--c-muted)}h1{font-size:38px;margin:10px 0}.portal header>p:last-child{color:var(--c-muted);line-height:1.8}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;padding-top:32px}.cards>a{display:flex;flex-direction:column;min-height:200px;border:1px solid var(--c-line);padding:22px;color:inherit}.cards small,.cards p,.cards span{color:var(--c-muted);font-size:12px;line-height:1.8}.cards h2{font-size:19px;margin:16px 0 8px}.cards span{margin-top:auto;padding-top:15px}.empty{padding:50px;text-align:center;color:var(--c-muted)}.logout{margin-top:35px;border:1px solid var(--c-line);background:white;padding:10px 16px;cursor:pointer}@media(max-width:800px){.cards{grid-template-columns:1fr 1fr}}@media(max-width:520px){.cards{grid-template-columns:1fr}h1{font-size:32px}}</style>
